#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${domain}
users:
  - default
  - name: pve
    passwd: $6$O7nJ.HIFYmCWZVG3$oWBVfI6QB/HQGYqsLWS11BwW9qYiFpMoC7mIg6NNCPOLujtws/glQjBGY1MVb7lJBK0U2oiczucX5KLYkyhfi/
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
